import { existsSync, readdirSync } from 'node:fs';
import { cwd } from 'node:process';

import { describe, expect, it } from 'vitest';

import {
  LANDING_FORMATS,
  LANDING_IMAGES,
  landingFile,
  landingHeight,
  type LandingImage,
} from './landingImages';

/**
 * The ladder in `landingImages.ts` and the files in `public/landing/` must describe each other
 * exactly, in both directions.
 *
 * **In scope per the testing policy's "project-wide invariants that silently rot", and nothing
 * else in the gate can see either failure.** `landingImages.ts` is what the `srcset` is built
 * from, and the derivatives are generated by a script that is deliberately NOT part of `build`
 * (the originals are outside the repo). So:
 *
 *  - a rung added to the ladder without re-running the script is a **404 in production**, on the
 *    exact candidate a wide-screen visitor picks. `format:check`, `lint`, `typecheck`, `build` and
 *    every other test stay green: a `srcset` is a string, and `<img>` fails silently by design.
 *  - a rung REMOVED from the ladder leaves orphaned files behind, which is committed dead weight
 *    nobody notices — this happened while writing the ladder (a 2560 rung was generated, measured,
 *    and dropped, leaving 1.8 MB of unreferenced AVIF and WebP).
 *  - a rung that does not FIT inside the original upscales, and an upscaled photo does not fail,
 *    it just looks soft. The generator throws on this too, but the generator does not run in CI
 *    and cannot: the originals are not in the repo. That is what `sourceSize` is for.
 *
 * This is deliberately NOT a test of the landing page's markup or CSS, which the policy excludes
 * as presentational, and not a restatement of the ladder: the assertion is that two independent
 * artefacts agree.
 *
 * `process.cwd()`, not `import.meta.url` — under jsdom the latter is an `http://localhost` URL.
 * Vitest runs from `web/`.
 */
const PUBLIC_DIR = `${cwd()}/public`;

const IMAGES = Object.values(LANDING_IMAGES) as readonly LandingImage[];

/** Every path the `srcset`s and the `src` reference, exactly as `LandingPicture` builds them. */
function referenced(): string[] {
  return IMAGES.flatMap((image) => [
    ...LANDING_FORMATS.flatMap(({ extension }) =>
      image.widths.map((width) => landingFile(image, width, extension)),
    ),
    ...image.fallbackWidths.map((width) => landingFile(image, width, 'jpg')),
    landingFile(image, image.fallbackWidth, 'jpg'),
  ]);
}

/** Everything in the directory except OS cruft — `.DS_Store` is the one this has to tolerate. */
function entries(): string[] {
  return readdirSync(`${PUBLIC_DIR}/landing`).filter((name) => !name.startsWith('.'));
}

const isDerivative = (name: string) => /\.(avif|webp|jpg)$/.test(name);

function onDisk(): string[] {
  return entries()
    .filter(isDerivative)
    .map((name) => `landing/${name}`);
}

describe('the landing image ladder', () => {
  const paths = [...new Set(referenced())];

  it('is not empty, so the assertions below are not vacuous', () => {
    expect(IMAGES.length).toBe(6);
    expect(paths.length).toBeGreaterThan(20);
  });

  it.each(paths)('%s exists in public/', (path) => {
    expect(existsSync(`${PUBLIC_DIR}/${path}`)).toBe(true);
  });

  it('leaves no orphaned derivative in public/landing', () => {
    expect(onDisk().filter((name) => !paths.includes(name))).toEqual([]);
  });

  // BOTH dimensions, because a crop taller than the original's ratio makes height the binding
  // constraint: `chimney-effort` is cut to 4:5 from a 3:2 original, so its 1920px rung needs
  // 2400px of source height while asking for barely a third of the source width. The rule that
  // used to be here only looked at width, and only at one image.
  it.each(IMAGES)('$slug never asks for a rung larger than its original', (image) => {
    const [sourceW, sourceH] = image.sourceSize;
    for (const width of [...image.widths, ...image.fallbackWidths, image.fallbackWidth]) {
      expect(width, `${image.slug} ${width}w exceeds the original's width`).toBeLessThanOrEqual(
        sourceW,
      );
      expect(
        landingHeight(image, width),
        `${image.slug} ${width}w needs more height than the original has`,
      ).toBeLessThanOrEqual(sourceH);
    }
  });

  // `PHOTO-CREDITS.md` used to live in this directory. It moved to `web/PHOTO-CREDITS.md` because
  // anything under `public/` ships in the app and is a candidate for the service-worker precache,
  // and a provenance record is a repo concern rather than a runtime one. This is what stops it —
  // or any other stray documentation — drifting back in.
  it('holds nothing but the derivatives, so no document can drift back into public/', () => {
    expect(entries().filter((name) => !isDerivative(name))).toEqual([]);
  });

  it('positive control: both directions detect a mismatch', () => {
    // Without these, "every referenced file exists" and "no file is unreferenced" both pass on an
    // empty list, which is indistinguishable from a broken path builder.
    expect(existsSync(`${PUBLIC_DIR}/landing/hero-granite-4096.avif`)).toBe(false);
    expect(onDisk()).toContain('landing/hero-granite-1920.avif');
    expect(paths).toContain('landing/hero-granite-1920.avif');
    expect(paths).not.toContain('landing/hero-granite-2560.avif');
    // The upscale rule is only meaningful if `sourceSize` is populated and the heights are real.
    expect(LANDING_IMAGES.detail.sourceSize).toEqual([960, 640]);
    expect(landingHeight(LANDING_IMAGES.effort, 1920)).toBe(2400);
    expect(landingHeight(LANDING_IMAGES.hero, 1920)).toBe(1280);
  });
});
