"""No comment may outgrow its tier's cap unless the allowlist names it with a reason.
Prose is the one thing in this repo nothing else checks: `ruff`, `tsc` and every other gate read
right past a forty-line docstring that stopped being true three PRs ago. A long comment is allowed,
but only with a signature next to it. **What it CANNOT catch:** whether the content is worth its
length, or whether it is true — a green run means "every exception is registered", never "the
comments are good".

The allowlist is `tests/comment_budget_allowlist.toml`, anchored on CONTENT and QUALNAMES, never
line numbers; five staleness arms below make an unearned entry a hard failure.
"""

import ast
import tomllib
from dataclasses import dataclass, replace
from datetime import date
from pathlib import Path
from typing import Final

import pytest

from server.settings import ROOT

ALLOWLIST_PATH: Final = ROOT / "tests" / "comment_budget_allowlist.toml"

# The caps, by tier. Two lines is enough for "why", which is the only thing a comment owes.
CAP: Final = 2
# Module docstrings get more: they are the one place a file's decisions may be written out.
MODULE_DOCSTRING_CAP: Final = 10
# Wire-contract docstrings get the most: FastAPI ships them to API consumers as the OpenAPI
# `description`, so their audience is outside this repo and cannot read the code instead.
WIRE_CONTRACT_CAP: Final = 20

CAPS: Final = {"module": MODULE_DOCSTRING_CAP, "wire": WIRE_CONTRACT_CAP, "plain": CAP}

# The ratchet. Entries whose reason starts with BASELINE are the un-reviewed backlog; new
# comments obey the cap from day one, so this number may only ever go DOWN. Lower it in the
# same PR that trims the comments — never raise it.
BASELINE_RATCHET: Final = 990

# The DEADLINE. The ratchet stops the backlog GROWING; nothing stops it sitting, and a register
# where every row still reads "not yet reviewed" a year from now is a freeze, not a cleanup. Each
# milestone is a date and the most BASELINE rows that may remain once it has passed: green until
# the date, then hard red until the count is at or below the target. The last target is 0, so the
# backlog has an end rather than a floor.
#
# ⚠️ **Editing a number cannot buy silence, by construction.** A target may never exceed
# `BASELINE_RATCHET - MILESTONE_MIN_CUT`, the ratchet may only ever go DOWN, and the ratchet may
# not sit more than 25 above the real count (`test_the_ratchet_is_not_slack`). `MILESTONE_MIN_CUT`
# is deliberately larger than that 25, so raising a target far enough to matter would mean raising
# the ratchet further than its own arm allows. The only move left is trimming comments.
BASELINE_DEADLINE: Final = (
    (date(2026, 12, 1), 800),
    (date(2027, 3, 1), 550),
    (date(2027, 6, 1), 275),
    (date(2027, 9, 1), 0),
)
# Larger than the ratchet's 25 of permitted slack, so the ratchet's own arm is what refuses an
# inflated target rather than this one having to guess at a motive.
MILESTONE_MIN_CUT: Final = 150

# Minimum characters of a real reason. "legacy" is not a register entry.
MIN_REASON_LENGTH: Final = 40
# Minimum characters of an anchor, so a short phrase cannot match half the file.
MIN_ANCHOR_LENGTH: Final = 30

SCOPE: Final = ("server", "migrations", "tests", "web/src", ".github")
KINDS: Final = ("hash_run", "docstring", "slash_run", "block")
# `.github/` is in scope for its workflows: a `#` run there is prose nothing else in the gate
# reads, which is how 15- and 28-line runs grew in two files no cap applied to.
YAML_SUFFIXES: Final = {".yml", ".yaml"}
SCOPED_SUFFIXES: Final = {".py", ".ts", ".tsx"} | YAML_SUFFIXES

# Detected by MARKER, not by path: a path list rots the moment a generator's output moves,
# whereas the marker travels with the file. Two generators, two spellings — TanStack Router
# writes its own banner and would overwrite anything we put there.
GENERATED_MARKERS: Final = (
    "GENERATED FILE — do not edit by hand.",
    "This file was automatically generated by TanStack Router.",
)
GENERATED_MARKER_SCAN_LINES: Final = 40
# Pinned so a third generated file has to be added here deliberately instead of appearing —
# and silently exempting itself from every comment rule in the repo.
GENERATED_FILE_COUNT: Final = 2


@dataclass(frozen=True, slots=True)
class Comment:
    """One comment found by one detector. `anchor` is the FULL normalised identity."""

    path: str
    kind: str
    anchor: str
    span: int
    line: int
    tier: str

    @property
    def cap(self) -> int:
        return CAPS[self.tier]


@dataclass(frozen=True, slots=True)
class Entry:
    """One allowlist row. `anchor` is a PREFIX of a `Comment.anchor`."""

    path: str
    kind: str
    anchor: str
    limit: int
    reason: str


# ---------------------------------------------------------------------------------
# Normalisation and anchoring
# ---------------------------------------------------------------------------------
#
# Line numbers are forbidden as anchors: every entry would rot on the next unrelated edit
# above it, and a register that rots is a register nobody reads. So comment runs anchor on
# their own CONTENT with markers, punctuation and whitespace collapsed away (a typo fix or a
# reflow must not orphan the entry), and docstrings anchor on the dotted qualname — which
# survives any move and breaks only on a RENAME, exactly when the exception wants re-reading.


def normalise(text: str) -> str:
    """Markers, punctuation and whitespace collapsed; lowercased. Unicode-aware."""
    kept = [character if character.isalnum() else " " for character in text]
    return " ".join("".join(kept).split()).lower()


def anchor_prefix(anchor: str) -> str:
    """The shortest whole-word prefix of `anchor` reaching MIN_ANCHOR_LENGTH."""
    prefix = ""
    for word in anchor.split():
        prefix = f"{prefix} {word}".strip()
        if len(prefix) >= MIN_ANCHOR_LENGTH:
            break
    return prefix


# ---------------------------------------------------------------------------------
# File scope
# ---------------------------------------------------------------------------------


def _is_generated(path: Path) -> bool:
    head = "\n".join(path.read_text(encoding="utf-8").splitlines()[:GENERATED_MARKER_SCAN_LINES])
    return any(marker in head for marker in GENERATED_MARKERS)


def _candidates() -> list[Path]:
    found: list[Path] = []
    for root in SCOPE:
        for path in sorted((ROOT / root).rglob("*")):
            if not path.is_file() or "__pycache__" in path.parts:
                continue
            if path.suffix not in SCOPED_SUFFIXES:
                continue
            found.append(path)
    return found


def generated_files() -> list[Path]:
    return [path for path in _candidates() if _is_generated(path)]


def scoped_files() -> list[Path]:
    return [path for path in _candidates() if not _is_generated(path)]


def _relative(path: Path) -> str:
    """Repo-relative, but tolerant: the meta-guards below feed it synthetic paths."""
    if path.is_absolute() and path.is_relative_to(ROOT):
        return path.relative_to(ROOT).as_posix()
    return path.as_posix()


def _dotted(path: Path) -> str:
    return ".".join(Path(_relative(path)).with_suffix("").parts)


# ---------------------------------------------------------------------------------
# Wire contracts — detected BY SHAPE, not by file
# ---------------------------------------------------------------------------------
#
# Exempting the whole of `server/**/routes.py` would over-exempt by half: those files hold far
# more long docstrings than they hold wire contracts. The shape is what earns the bigger cap —
# a `@router.<verb>(...)` decorator, or a `BaseModel` base — because that is what puts the
# docstring in the OpenAPI document where an outside consumer reads it.


def _is_router_decorated(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        func = decorator.func
        if isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name):
            if func.value.id.endswith("router"):
                return True
    return False


def _is_base_model(node: ast.ClassDef) -> bool:
    for base in node.bases:
        if isinstance(base, ast.Name) and base.id == "BaseModel":
            return True
        if isinstance(base, ast.Attribute) and base.attr == "BaseModel":
            return True
    return False


# ---------------------------------------------------------------------------------
# The four detectors
# ---------------------------------------------------------------------------------


def _docstrings(path: Path, tree: ast.Module) -> tuple[list[Comment], list[range]]:
    """Docstring comments, plus the line ranges they occupy (so `#` runs can skip them)."""
    module = _dotted(path)
    is_routes = path.name == "routes.py" and path.parts[-3] == "server"
    comments: list[Comment] = []
    ranges: list[range] = []

    def walk(node: ast.AST, qualname: str) -> None:
        body = getattr(node, "body", None)
        if isinstance(node, ast.Module | ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            if ast.get_docstring(node, clean=False) is not None and body:
                literal = body[0]
                assert literal.end_lineno is not None
                # Span from the source positions, not the string value: that is exactly the
                # block of lines a reader scrolls past, quotes included.
                span = literal.end_lineno - literal.lineno + 1
                ranges.append(range(literal.lineno, literal.end_lineno + 1))
                tier = "plain"
                if isinstance(node, ast.Module):
                    tier = "module"
                elif is_routes and (
                    _is_base_model(node)
                    if isinstance(node, ast.ClassDef)
                    else _is_router_decorated(node)
                ):
                    tier = "wire"
                comments.append(
                    Comment(_relative(path), "docstring", qualname, span, literal.lineno, tier)
                )
        for child in ast.iter_child_nodes(node):
            if isinstance(child, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
                walk(child, f"{qualname}.{child.name}")
            elif not isinstance(child, ast.Module):
                walk(child, qualname)

    walk(tree, module)
    return comments, ranges


def _multiline_string_ranges(tree: ast.Module) -> list[range]:
    """Every string literal spanning more than one line — a `#` inside one is not a comment."""
    ranges: list[range] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if node.end_lineno is not None and node.end_lineno > node.lineno:
                ranges.append(range(node.lineno, node.end_lineno + 1))
    return ranges


def _own_line_runs(
    path: Path, lines: list[str], marker: str, kind: str, excluded: list[range]
) -> list[Comment]:
    """Consecutive lines whose `strip()` starts with `marker`. A blank line ends a run.

    Own-line only: a trailing comment after code is out of scope, because it cannot run long
    without the code running long with it.
    """
    skip = {number for span in excluded for number in span}
    comments: list[Comment] = []
    run: list[str] = []
    start = 0
    for number, raw in enumerate(lines, start=1):
        stripped = raw.strip()
        if stripped.startswith(marker) and number not in skip:
            if not run:
                start = number
            run.append(stripped)
            continue
        if run:
            comments.append(
                Comment(_relative(path), kind, normalise(" ".join(run)), len(run), start, "plain")
            )
            run = []
    if run:
        comments.append(
            Comment(_relative(path), kind, normalise(" ".join(run)), len(run), start, "plain")
        )
    return comments


def _yaml_runs(path: Path, lines: list[str]) -> list[Comment]:
    """Line 1 starts the FILE HEADER, which takes the module cap; every other run is plain."""
    runs = _own_line_runs(path, lines, "#", "hash_run", [])
    return [replace(run, tier="module") if run.line == 1 else run for run in runs]


def _block_comments(path: Path, source: str) -> tuple[list[Comment], list[range]]:
    """`/* ... */`, JSDoc included. Span is newlines + 1.

    Boundary handling follows `web/src/test/sourceScan.ts` — the non-greedy `[\\s\\S]*?` to the
    first `*/`. A string literal containing `/*` is a known false positive and takes an
    allowlist entry; loosening the scan to dodge it would blind the detector.
    """
    comments: list[Comment] = []
    ranges: list[range] = []
    index = 0
    while (open_at := source.find("/*", index)) != -1:
        close_at = source.find("*/", open_at + 2)
        if close_at == -1:
            break
        body = source[open_at : close_at + 2]
        span = body.count("\n") + 1
        first = source.count("\n", 0, open_at) + 1
        comments.append(Comment(_relative(path), "block", normalise(body), span, first, "plain"))
        ranges.append(range(first, first + span))
        index = close_at + 2
    return comments, ranges


def collect() -> list[Comment]:
    """Every comment in scope, from all four detectors."""
    comments: list[Comment] = []
    for path in scoped_files():
        source = path.read_text(encoding="utf-8")
        lines = source.splitlines()
        if path.suffix == ".py":
            tree = ast.parse(source, filename=str(path))
            docstrings, docstring_ranges = _docstrings(path, tree)
            comments.extend(docstrings)
            excluded = docstring_ranges + _multiline_string_ranges(tree)
            comments.extend(_own_line_runs(path, lines, "#", "hash_run", excluded))
        elif path.suffix in YAML_SUFFIXES:
            comments.extend(_yaml_runs(path, lines))
        else:
            blocks, block_ranges = _block_comments(path, source)
            comments.extend(blocks)
            comments.extend(_own_line_runs(path, lines, "//", "slash_run", block_ranges))
    return comments


def over_cap() -> list[Comment]:
    return [comment for comment in collect() if comment.span > comment.cap]


# ---------------------------------------------------------------------------------
# The allowlist
# ---------------------------------------------------------------------------------


def entries() -> list[Entry]:
    with ALLOWLIST_PATH.open("rb") as handle:
        document = tomllib.load(handle)
    rows = document.get("exception", [])
    assert isinstance(rows, list), "the allowlist must be a list of [[exception]] tables"
    return [
        Entry(
            path=str(row["path"]),
            kind=str(row["kind"]),
            anchor=str(row["anchor"]),
            limit=int(row["limit"]),
            reason=str(row["reason"]),
        )
        for row in rows
    ]


def _matches(entry: Entry, comments: list[Comment]) -> list[Comment]:
    return [
        comment
        for comment in comments
        if comment.path == entry.path
        and comment.kind == entry.kind
        and (
            comment.anchor == entry.anchor
            if entry.kind == "docstring"
            else comment.anchor.startswith(entry.anchor)
        )
    ]


@pytest.fixture(scope="module")
def comments() -> list[Comment]:
    return collect()


@pytest.fixture(scope="module")
def allowlist() -> list[Entry]:
    return entries()


# ---------------------------------------------------------------------------------
# The invariant
# ---------------------------------------------------------------------------------


def test_no_comment_exceeds_its_cap_without_an_allowlist_entry(
    comments: list[Comment], allowlist: list[Entry]
) -> None:
    """The budget itself. Trim the comment, or register it with a reason."""
    registered = {
        (comment.path, comment.kind, comment.anchor)
        for entry in allowlist
        for comment in _matches(entry, comments)
    }
    unregistered = [
        comment
        for comment in comments
        if comment.span > comment.cap
        and (comment.path, comment.kind, comment.anchor) not in registered
    ]
    formatted = "\n".join(
        f"  {comment.path}:{comment.line} {comment.kind} ({comment.tier} tier) "
        f"{comment.span} lines > cap {comment.cap}"
        for comment in unregistered[:20]
    )
    assert not unregistered, (
        f"{len(unregistered)} comment(s) are over their cap with no allowlist entry. Trim them, "
        f"or add an [[exception]] to tests/comment_budget_allowlist.toml with a real reason:\n"
        f"{formatted}"
    )


def test_every_allowlisted_comment_is_within_its_declared_limit(
    comments: list[Comment], allowlist: list[Entry]
) -> None:
    """`limit` is a CEILING, never an equality — an exact match would fire on a typo fix."""
    breached = [
        (entry, comment)
        for entry in allowlist
        for comment in _matches(entry, comments)
        if comment.span > entry.limit
    ]
    formatted = "\n".join(
        f"  {entry.path} {entry.kind} '{entry.anchor[:40]}...' grew to {comment.span} "
        f"lines, limit {entry.limit}"
        for entry, comment in breached[:20]
    )
    assert not breached, (
        f"{len(breached)} allowlisted comment(s) grew past their declared limit. An exception "
        f"is for a comment that is already long, not a licence to keep going:\n{formatted}"
    )


# ---------------------------------------------------------------------------------
# The five staleness arms — the allowlist must not be allowed to rot
# ---------------------------------------------------------------------------------
#
# An allowlist nobody can be wrong about is an allowlist nobody re-reads. Every arm below is a
# HARD failure, because the failure mode being prevented is the register slowly turning into a
# list of comments that no longer exist.


def test_no_allowlist_anchor_resolves_to_nothing(
    comments: list[Comment], allowlist: list[Entry]
) -> None:
    """Arm 1. The comment was deleted or reworded past its anchor; the entry must go too."""
    orphans = [entry for entry in allowlist if not _matches(entry, comments)]
    formatted = "\n".join(f"  {entry.path} {entry.kind} '{entry.anchor}'" for entry in orphans[:20])
    assert not orphans, (
        f"{len(orphans)} allowlist entry(ies) match no comment. Either the comment is gone — "
        f"delete the entry — or it was reworded and the entry needs re-reading, not "
        f"re-anchoring on autopilot:\n{formatted}"
    )


def test_no_allowlist_entry_covers_a_comment_that_is_now_within_its_cap(
    comments: list[Comment], allowlist: list[Entry]
) -> None:
    """Arm 2. It was trimmed. The exception is no longer earned and stops being a licence."""
    earned = [
        (entry, comment)
        for entry in allowlist
        for comment in _matches(entry, comments)
        if comment.span <= comment.cap
    ]
    formatted = "\n".join(
        f"  {entry.path} {entry.kind} '{entry.anchor[:40]}' is now {comment.span} "
        f"lines (cap {comment.cap})"
        for entry, comment in earned[:20]
    )
    assert not earned, (
        f"{len(earned)} allowlist entry(ies) cover a comment that now fits its cap. Someone "
        f"did the work — delete the entry so the cap applies again:\n{formatted}"
    )


def test_no_allowlist_anchor_is_ambiguous(comments: list[Comment], allowlist: list[Entry]) -> None:
    """Arm 3. Two matches means the entry exempts a comment nobody reviewed."""
    ambiguous = [(entry, _matches(entry, comments)) for entry in allowlist]
    ambiguous = [(entry, found) for entry, found in ambiguous if len(found) > 1]
    formatted = "\n".join(
        f"  {entry.path} {entry.kind} '{entry.anchor}' matches {len(found)} comments "
        f"(lines {[comment.line for comment in found]})"
        for entry, found in ambiguous[:20]
    )
    assert not ambiguous, (
        f"{len(ambiguous)} allowlist anchor(s) match more than one comment, so each exempts "
        f"something that was never reviewed. Lengthen the anchor:\n{formatted}"
    )


def test_every_allowlist_entry_carries_a_real_reason(allowlist: list[Entry]) -> None:
    """Arm 4. An allowlist reading "legacy" is not a register, it is a rubber stamp."""
    thin = [entry for entry in allowlist if len(entry.reason.strip()) < MIN_REASON_LENGTH]
    formatted = "\n".join(f"  {entry.path} {entry.kind}: {entry.reason!r}" for entry in thin[:20])
    assert not thin, (
        f"{len(thin)} allowlist entry(ies) have a reason under {MIN_REASON_LENGTH} characters. "
        f"Say what the length buys and who reads it:\n{formatted}"
    )


def test_the_baseline_backlog_only_shrinks(allowlist: list[Entry]) -> None:
    """Arm 5, the ratchet. New comments obey the cap; the backlog is one-way."""
    baseline = [entry for entry in allowlist if entry.reason.startswith("BASELINE")]
    assert len(baseline) <= BASELINE_RATCHET, (
        f"{len(baseline)} BASELINE entries, ratchet is {BASELINE_RATCHET}. A new comment over "
        f"the cap must be trimmed or given a real reason — it may not join the backlog."
    )


def test_the_ratchet_is_not_slack(allowlist: list[Entry]) -> None:
    """The ratchet has to be PINNED to reality, or arm 5 stops meaning anything.

    Left loose, `BASELINE_RATCHET` would drift upward as a matter of course. Requiring it to
    track the real count within a small margin means burning down the backlog and lowering the
    number happen in the same diff.
    """
    baseline = [entry for entry in allowlist if entry.reason.startswith("BASELINE")]
    assert BASELINE_RATCHET - len(baseline) <= 25, (
        f"BASELINE_RATCHET is {BASELINE_RATCHET} but only {len(baseline)} entries remain. "
        f"Lower the ratchet in this PR — slack in it is a comment budget nobody is holding to."
    )


def _milestones_due(count: int, today: date) -> list[tuple[date, int]]:
    """Milestones whose date has arrived and whose target `count` still exceeds."""
    return [(due, target) for due, target in BASELINE_DEADLINE if today >= due and count > target]


def test_the_baseline_backlog_is_burned_down_on_schedule(allowlist: list[Entry]) -> None:
    """The deadline. A backlog the ratchet has merely frozen is not a backlog being cleared."""
    baseline = [entry for entry in allowlist if entry.reason.startswith("BASELINE")]
    due = _milestones_due(len(baseline), date.today())
    formatted = "\n".join(
        f"  by {when.isoformat()}: at most {target} BASELINE rows — "
        f"trim or justify {len(baseline) - target} more"
        for when, target in due
    )
    assert not due, (
        f"{len(baseline)} BASELINE rows remain and a burn-down milestone has passed. Trim the "
        f"comments, or replace the BASELINE reason with a real one, until the count fits:\n"
        f"{formatted}"
    )


def test_the_deadline_schedule_demands_a_real_cut() -> None:
    """The deadline's anti-slack arm: a target nobody has to meet is a date, not a deadline."""
    dates = [due for due, _ in BASELINE_DEADLINE]
    targets = [target for _, target in BASELINE_DEADLINE]
    assert dates == sorted(set(dates)), "milestones must be in strictly increasing date order"
    assert targets == sorted(set(targets), reverse=True), "each target must be below the last"
    assert targets[-1] == 0, "the final milestone must retire the backlog, not park it"
    assert targets[0] <= BASELINE_RATCHET - MILESTONE_MIN_CUT, (
        f"the first target is {targets[0]}, which is not {MILESTONE_MIN_CUT} below the ratchet "
        f"({BASELINE_RATCHET}). Raising a target only works by raising the ratchet, which "
        f"test_the_ratchet_is_not_slack refuses — lower the target instead."
    )


def test_the_deadline_arm_goes_red_once_a_milestone_has_passed() -> None:
    """Positive control. A deadline nobody has watched fire is a deadline nobody should trust."""
    first_due, first_target = BASELINE_DEADLINE[0]
    assert _milestones_due(first_target + 1, first_due) == [(first_due, first_target)]
    assert _milestones_due(first_target, first_due) == []
    last_due, _ = BASELINE_DEADLINE[-1]
    assert _milestones_due(1, last_due) == [BASELINE_DEADLINE[-1]]
    assert _milestones_due(0, last_due) == []


# ---------------------------------------------------------------------------------
# Meta-guards: the detectors and the scope, positive-controlled
# ---------------------------------------------------------------------------------


def test_the_hash_detector_sees_a_run_and_stops_at_a_blank_line(tmp_path: Path) -> None:
    """Positive control. A detector that cannot see its own violation is worse than none."""
    path = tmp_path / "sample.py"
    lines = ["# one", "# two", "# three", "", "# four", "x = 1  # trailing, out of scope"]
    found = _own_line_runs(path, lines, "#", "hash_run", [])
    assert [comment.span for comment in found] == [3, 1]


def test_the_hash_detector_ignores_a_hash_inside_a_multiline_string() -> None:
    """The false positive worth excluding by PARSING rather than by loosening the scan."""
    source = 'X = """\n# not a comment\n# still not\n# nor this\n"""\n'
    tree = ast.parse(source)
    found = _own_line_runs(
        Path("sample.py"), source.splitlines(), "#", "hash_run", _multiline_string_ranges(tree)
    )
    assert found == []


def test_the_slash_and_block_detectors_do_not_double_count_or_eat_a_url() -> None:
    """`//` inside a `/* */` must not count twice, and a URL is not a comment."""
    source = "/*\n * a\n * b\n */\nconst u = 'https://example.com/a//b';\n// tail\n// tail two\n"
    blocks, ranges = _block_comments(Path("sample.ts"), source)
    assert [comment.span for comment in blocks] == [4]
    slashes = _own_line_runs(Path("sample.ts"), source.splitlines(), "//", "slash_run", ranges)
    assert [comment.span for comment in slashes] == [2]


def test_the_yaml_header_takes_the_module_cap_and_a_later_run_does_not(tmp_path: Path) -> None:
    """Positive control on the two YAML tiers — a header is a file's decisions, a run is a why."""
    lines = ["# one", "# two", "", "jobs:", "  # three", "  # four"]
    found = _yaml_runs(tmp_path / "sample.yml", lines)
    assert [(comment.tier, comment.cap, comment.span) for comment in found] == [
        ("module", MODULE_DOCSTRING_CAP, 2),
        ("plain", CAP, 2),
    ]


def test_the_workflows_are_in_scope_so_a_regrown_comment_run_is_caught() -> None:
    """`.github/` was out of scope twice over, by root and by suffix — hence two long runs."""
    scoped = {_relative(path) for path in scoped_files()}
    assert ".github/workflows/ci.yml" in scoped
    assert ".github/workflows/migrate.yml" in scoped


def test_the_docstring_detector_counts_the_lines_a_reader_sees() -> None:
    """Including the quote lines, because those are lines in the file too."""
    source = 'def f() -> None:\n    """One.\n\n    Two.\n    """\n'
    found, _ = _docstrings(Path("sample.py"), ast.parse(source))
    assert [(comment.anchor, comment.span) for comment in found] == [("sample.f", 4)]


def test_the_wire_contract_shape_is_the_one_this_repo_actually_uses() -> None:
    """Verified against the real decorators, not against a remembered spelling.

    If the router import is ever aliased or the verb call is wrapped, this fails here rather
    than silently demoting thirty-four OpenAPI descriptions to the two-line cap.
    """
    routes = ROOT / "server" / "plans" / "routes.py"
    found, _ = _docstrings(routes, ast.parse(routes.read_text(encoding="utf-8")))
    wire = {comment.anchor for comment in found if comment.tier == "wire"}
    assert "server.plans.routes.create_plan" in wire, "no @router-decorated function was seen"
    assert "server.plans.routes.PlanOut" in wire, "no BaseModel response class was seen"
    assert "server.plans.routes" not in wire, "the module docstring is not a wire contract"


def test_the_wire_tier_does_not_swallow_the_whole_routes_file(comments: list[Comment]) -> None:
    """The shape check has to be NARROWER than the file, or it is just a path exemption.

    Exempting `server/**/routes.py` wholesale would over-exempt by roughly half. Asserting the
    non-wire docstrings still outnumber nothing keeps that distinction load-bearing.
    """
    in_routes = [
        comment
        for comment in comments
        if comment.path.endswith("routes.py") and comment.kind == "docstring"
    ]
    plain = [comment for comment in in_routes if comment.tier == "plain"]
    assert plain, "every docstring in every routes.py read as a wire contract — shape is too wide"


def test_exactly_the_known_generated_files_are_skipped() -> None:
    """Pinned cardinality: a third generated file is a deliberate edit here, not a surprise."""
    skipped = [_relative(path) for path in generated_files()]
    assert len(skipped) == GENERATED_FILE_COUNT, (
        f"expected {GENERATED_FILE_COUNT} generated file(s) to be skipped, found "
        f"{len(skipped)}: {skipped}. A file that exempts itself from every comment rule in "
        f"the repo by carrying a banner must be acknowledged here."
    )


def test_every_migration_revision_is_in_scope_alongside_migration_env() -> None:
    """There is no wholesale path skip left: a future revision is born budgeted, not exempt."""
    scoped = {_relative(path) for path in scoped_files()}
    assert "migrations/env.py" in scoped, "migrations/env.py is live code and stays in scope"
    revisions = sorted(path for path in scoped if path.startswith("migrations/versions/"))
    assert len(revisions) >= 8, f"only {len(revisions)} revision(s) in scope: {revisions}"


def test_the_allowlist_declares_only_known_kinds(allowlist: list[Entry]) -> None:
    """A typo'd `kind` would match no comment and quietly exempt nothing — or everything."""
    unknown = sorted({entry.kind for entry in allowlist} - set(KINDS))
    assert not unknown, f"unknown kind(s) in the allowlist: {unknown}; expected one of {KINDS}"


def test_no_allowlist_anchor_carries_a_line_number(allowlist: list[Entry]) -> None:
    """Anchors are content and qualnames. A line number rots on the next unrelated edit."""
    numeric = [entry for entry in allowlist if entry.anchor.strip().isdigit()]
    assert not numeric, f"{len(numeric)} anchor(s) are line numbers; anchor on content instead"


def test_every_allowlist_anchor_is_long_enough_to_identify_one_comment(
    comments: list[Comment], allowlist: list[Entry]
) -> None:
    """Short anchors are how arm 3 gets defeated: match everything, review nothing."""
    by_identity = {(comment.path, comment.kind, comment.anchor) for comment in comments}
    short = [
        entry
        for entry in allowlist
        if len(entry.anchor) < MIN_ANCHOR_LENGTH
        and (entry.path, entry.kind, entry.anchor) not in by_identity
    ]
    formatted = "\n".join(f"  {entry.path} {entry.kind} '{entry.anchor}'" for entry in short[:20])
    assert not short, (
        f"{len(short)} anchor(s) are under {MIN_ANCHOR_LENGTH} characters and are not the "
        f"comment's whole normalised text:\n{formatted}"
    )
