"""The OpenAPI document, canonically serialised — the input to the TypeScript codegen.

`npm run codegen:api` pipes this module's stdout into
`web/scripts/gen-api-types.mjs`, which turns it into `web/src/api/schema.ts`. The
generated file is **committed**, for the same reason `src/routeTree.gen.ts` is: the `web`
CI job and Vercel's SPA build have Node and no Python, so nothing in that half of the
build can produce it.

## Staleness is caught by a FINGERPRINT, not by re-running the generator

The generated file carries `openapi-sha256: <hex>` in its header — the hash of exactly
the bytes this module printed. `tests/test_vocabulary_contract.py` recomputes it from the
live application and fails when the two differ, so "someone added an endpoint and forgot
to regenerate" is caught by `pytest`, in the local gate, with no Node and no network.

That is a deliberately narrow claim, and worth stating precisely:

- it proves the committed types were generated from **this** API surface;
- it does **not** prove they were generated by the same `openapi-typescript` version, and
  it cannot — the hash is over the input, not the output.

**`info.version` is normalised away before hashing.** It comes from the root
`package.json`, so without this every `npm run version:dev` would invalidate the
fingerprint over a string that appears nowhere in the generated types. The document
printed here is therefore not suitable for anything but codegen; the *served* schema
(`/api/openapi.json`, non-production only) carries the real version.
"""

import hashlib
import json
import sys
from typing import Any, Final

from server.app import app

# What `info.version` is replaced with. Any fixed string works; this one says why.
VERSION_PLACEHOLDER: Final = "0.0.0-codegen"


def schema_document() -> dict[str, Any]:
    """The application's OpenAPI document, with the version pinned to a placeholder."""
    document: dict[str, Any] = json.loads(json.dumps(app.openapi()))
    info = document.get("info")
    if isinstance(info, dict):
        info["version"] = VERSION_PLACEHOLDER
    return document


def canonical_json() -> str:
    """One byte-for-byte serialisation, so both sides of the fingerprint agree.

    `sort_keys` because Python dict order is an implementation detail of how FastAPI
    happened to build the document, and a reordering is not a change to the API.
    """
    return json.dumps(schema_document(), sort_keys=True, separators=(",", ":"))


def fingerprint() -> str:
    """SHA-256 of `canonical_json()`, hex. The value written into the generated header."""
    return hashlib.sha256(canonical_json().encode("utf-8")).hexdigest()


def main() -> None:
    """`uv run python -m server.openapi_schema` — stdout is the codegen's input.

    `write`, not `print`: the generator hashes the bytes it receives, so a trailing
    newline here would make every fingerprint disagree with `fingerprint()` by one byte.
    """
    sys.stdout.write(canonical_json())


if __name__ == "__main__":
    main()
