"""grade ladder: grade_system + grade, and the discipline enum

Revision ID: 0001
Revises:
Create Date: 2026-08-12

The first migration. It creates the reference tables behind the shared grade ordinal
ladder (see server/domain/grades.py) and the native `discipline` enum type.

Hand-written rather than autogenerated, because there is no database to autogenerate
against on the machine this was written on — CI is what proves it, by running
`alembic upgrade head` against a throwaway Postgres before pytest, plus `alembic check`
to prove it matches the models.

Constraint names are spelled out explicitly and match what `NAMING_CONVENTION` in
server/models.py derives, so `alembic check` sees no diff and a future
`op.drop_constraint` has a stable name to reference.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# create_type=False: the type is created (and dropped) explicitly below, so
# `op.create_table` does not also try to emit CREATE TYPE. Leaving it to the implicit
# path is what produces "type discipline already exists" on the second table to use it.
discipline = postgresql.ENUM("boulder", "sport", name="discipline", create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    # checkfirst so a partially-applied environment can be brought forward.
    discipline.create(bind, checkfirst=True)

    op.create_table(
        "grade_system",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("discipline", discipline, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_grade_system"),
        sa.UniqueConstraint("key", name="uq_grade_system_key"),
    )

    op.create_table(
        "grade",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grade_system_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=False),
        sa.Column("ordinal", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grade_system_id"],
            ["grade_system.id"],
            name="fk_grade_grade_system_id_grade_system",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_grade"),
        # The seed upserts on (grade_system_id, label).
        sa.UniqueConstraint("grade_system_id", "label", name="uq_grade_grade_system_id_label"),
        # One label per rung per scale — the invariant that makes the ladder a ladder.
        sa.UniqueConstraint("grade_system_id", "ordinal", name="uq_grade_grade_system_id_ordinal"),
    )
    op.create_index("ix_grade_ordinal", "grade", ["ordinal"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_grade_ordinal", table_name="grade")
    op.drop_table("grade")
    op.drop_table("grade_system")
    # Drop the type last: it cannot go while a column still uses it.
    discipline.drop(op.get_bind(), checkfirst=True)
