import { readdirSync, readFileSync } from 'node:fs';
import { cwd } from 'node:process';

import { createMemoryHistory } from '@tanstack/react-router';
import { describe, expect, it } from 'vitest';

import { createAuth } from './auth/AuthProvider';
import { createAppRouter, createQueryClient } from './router';

/**
 * The client mirror of `tests/test_auth_routes_enumerated.py`, and for the same reason: the
 * `_authed` directory convention protects a leaf by where its file sits, so the failure mode
 * is **omission** — a new route created next to `login.tsx` instead of inside `_authed/` is
 * silently public, and nothing else in the gate notices.
 *
 * So every route must be either explicitly listed below or a descendant of `_authed`. Making a
 * route public stays a visible line in a diff, exactly as `PUBLIC_ROUTES` is on the server.
 *
 * ## Why it reads the route FILES and not only the generated tree
 *
 * `routeTree.gen.ts` is committed and only regenerated by a build, and `check:web` runs `test`
 * before `build`. Checking the tree alone therefore made this guard blind on exactly the change
 * it exists to catch: adding `routes/settings.tsx` left it passing 3/3 until a build had run,
 * and the first CI failure was the post-build stale-file check — naming a stale file rather than
 * an unguarded route.
 *
 * So the id set under test is the **union** of the generated tree and the ids the route files
 * themselves declare. The declared id is the string literal the author passed to
 * `createFileRoute` / `createLazyFileRoute`, which the router plugin already validates against
 * the file's path, so this is reading an authored fact rather than re-deriving the generator's
 * naming rules. A new unguarded leaf now fails **as an unguarded route**, with no build.
 */
const PUBLIC_ROUTE_IDS: ReadonlySet<string> = new Set([
  '__root__',
  // The public landing page. It redirects an already-signed-in visitor to /dashboard, but
  // deliberately does not attempt a refresh — see routes/index.tsx.
  '/',
  // The catch-all. An unmatched URL must render "not found", not bounce to a login form.
  '/$',
  '/login',
  '/register',
]);

const GUARD_ID = '/_authed';

function freshRouter() {
  return createAppRouter(createMemoryHistory({ initialEntries: ['/'] }), {
    auth: createAuth(),
    queryClient: createQueryClient(),
  });
}

function treeIds(): string[] {
  return Object.keys(freshRouter().routesById);
}

// `process.cwd()`, not `import.meta.url`: under jsdom that is an `http://localhost` URL, so
// `fileURLToPath` throws "The URL must be of scheme file". Vitest runs from `web/`.
const ROUTES_DIR = `${cwd()}/src/routes`;

/** Every `.tsx` under `src/routes`, recursively. */
function routeFiles(dir = ROUTES_DIR): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = `${dir}/${entry.name}`;
    if (entry.isDirectory()) return routeFiles(path);
    return entry.isFile() && entry.name.endsWith('.tsx') ? [path] : [];
  });
}

/**
 * The route ids the FILES declare. `__root.tsx` uses `createRootRouteWithContext` and carries
 * no literal, so it drops out on its own — which is correct, it is not a leaf that can be
 * public by accident.
 */
function declaredIds(): string[] {
  const pattern = /create(?:Lazy)?FileRoute\(\s*'([^']+)'/g;
  return routeFiles().flatMap((file) =>
    [...readFileSync(file, 'utf8').matchAll(pattern)].map(([, id]) => id ?? ''),
  );
}

function allIds(): string[] {
  return [...new Set([...treeIds(), ...declaredIds()])];
}

function isGuarded(id: string): boolean {
  return id === GUARD_ID || id.startsWith(`${GUARD_ID}/`);
}

describe('every route is public on purpose or guarded', () => {
  it('has no route that is neither listed nor under the guard', () => {
    const unaccounted = allIds().filter((id) => !PUBLIC_ROUTE_IDS.has(id) && !isGuarded(id));

    expect(unaccounted).toEqual([]);
  });

  // Reads the files rather than the tree, so it fires on a brand-new leaf before any build.
  it('sees a route file the committed tree has not caught up with', () => {
    const declared = declaredIds();

    expect(declared.length).toBeGreaterThan(0);
    expect(declared.filter((id) => !treeIds().includes(id))).toEqual([]);
  });

  // Without this the assertion above would also pass on a tree with no guarded routes at all,
  // or with a `_authed` route that had lost its `beforeLoad`.
  it('positive control: the guard exists, carries a beforeLoad, and has leaves under it', () => {
    const router = freshRouter();
    const ids = Object.keys(router.routesById);
    // Reading the files must not be silently returning nothing, or the union above degrades
    // to the tree-only check this test exists to replace.
    expect(declaredIds()).toContain('/_authed/plan');

    expect(ids).toContain(GUARD_ID);
    // The directory convention is worth nothing if the layout route stops guarding.
    expect(router.routesById[GUARD_ID].options.beforeLoad).toBeTypeOf('function');
    expect(ids.filter((id) => id.startsWith(`${GUARD_ID}/`)).sort()).toEqual([
      '/_authed/dashboard',
      '/_authed/diary',
      '/_authed/plan',
      '/_authed/profile',
      '/_authed/session',
    ]);
  });

  it('does not list a route as public that no longer exists', () => {
    const ids = new Set(allIds());
    const stale = [...PUBLIC_ROUTE_IDS].filter((id) => !ids.has(id));

    expect(stale).toEqual([]);
  });
});
