/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'

const AuthedDiaryLazyRouteImport = createFileRoute('/_authed/diary')()
const AuthedOnboardingLazyRouteImport = createFileRoute('/_authed/onboarding')()
const AuthedPlanLazyRouteImport = createFileRoute('/_authed/plan')()
const AuthedProfileLazyRouteImport = createFileRoute('/_authed/profile')()
const AuthedSessionLazyRouteImport = createFileRoute('/_authed/session')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDiaryLazyRoute = AuthedDiaryLazyRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import('./routes/_authed/diary.lazy').then((d) => d.Route))
const AuthedOnboardingLazyRoute = AuthedOnboardingLazyRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/onboarding.lazy').then((d) => d.Route),
)
const AuthedPlanLazyRoute = AuthedPlanLazyRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import('./routes/_authed/plan.lazy').then((d) => d.Route))
const AuthedProfileLazyRoute = AuthedProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/profile.lazy').then((d) => d.Route),
)
const AuthedSessionLazyRoute = AuthedSessionLazyRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/session.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/diary': typeof AuthedDiaryLazyRoute
  '/onboarding': typeof AuthedOnboardingLazyRoute
  '/plan': typeof AuthedPlanLazyRoute
  '/profile': typeof AuthedProfileLazyRoute
  '/session': typeof AuthedSessionLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/diary': typeof AuthedDiaryLazyRoute
  '/onboarding': typeof AuthedOnboardingLazyRoute
  '/plan': typeof AuthedPlanLazyRoute
  '/profile': typeof AuthedProfileLazyRoute
  '/session': typeof AuthedSessionLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/diary': typeof AuthedDiaryLazyRoute
  '/_authed/onboarding': typeof AuthedOnboardingLazyRoute
  '/_authed/plan': typeof AuthedPlanLazyRoute
  '/_authed/profile': typeof AuthedProfileLazyRoute
  '/_authed/session': typeof AuthedSessionLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/diary'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/diary'
    | '/onboarding'
    | '/plan'
    | '/profile'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/dashboard'
    | '/_authed/diary'
    | '/_authed/onboarding'
    | '/_authed/plan'
    | '/_authed/profile'
    | '/_authed/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/diary': {
      id: '/_authed/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthedDiaryLazyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingLazyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plan': {
      id: '/_authed/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthedPlanLazyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileLazyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/session': {
      id: '/_authed/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AuthedSessionLazyRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDiaryLazyRoute: typeof AuthedDiaryLazyRoute
  AuthedOnboardingLazyRoute: typeof AuthedOnboardingLazyRoute
  AuthedPlanLazyRoute: typeof AuthedPlanLazyRoute
  AuthedProfileLazyRoute: typeof AuthedProfileLazyRoute
  AuthedSessionLazyRoute: typeof AuthedSessionLazyRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDiaryLazyRoute: AuthedDiaryLazyRoute,
  AuthedOnboardingLazyRoute: AuthedOnboardingLazyRoute,
  AuthedPlanLazyRoute: AuthedPlanLazyRoute,
  AuthedProfileLazyRoute: AuthedProfileLazyRoute,
  AuthedSessionLazyRoute: AuthedSessionLazyRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
