import js from '@eslint/js';
import a11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  // routeTree.gen.ts is generated by @tanstack/router-plugin on every dev/build run.
  // Never hand-edit it, and never lint it — mirrored in .prettierignore.
  { ignores: ['dist/**', 'coverage/**', 'src/routeTree.gen.ts'] },
  js.configs.recommended,

  // Type-aware linting. This is the reason the repo stays on TypeScript 6 —
  // typescript-eslint's peer range is >=4.8.4 <6.1.0, so TS 7 would silently cost
  // us the two rules below, which are exactly the ones an app with optimistic
  // writes and a background outbox needs.
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
      globals: globals.browser,
    },
    plugins: { 'react-hooks': reactHooks, 'jsx-a11y': a11y },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...a11y.flatConfigs.recommended.rules,
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      // `throw redirect({ to })` and `throw notFound()` are how TanStack Router's route guards
      // work, and neither return type is an Error — they are control flow the router catches,
      // not failures. Allowed by TYPE NAME so the rule keeps rejecting every other non-Error
      // throw: `throw new Response(...)`, and a locally-declared type that merely shares the
      // name, are both still errors (verified by trying them).
      //
      // Both entries resolve in `@tanstack/router-core`, where the two functions are declared
      // (`redirect.d.ts`, `not-found.d.ts`). An `@tanstack/react-router` entry looks like
      // belt-and-braces and is inert — the re-export does not change the declaring package —
      // so it is deliberately absent rather than kept "just in case".
      '@typescript-eslint/only-throw-error': [
        'error',
        {
          allow: [
            { from: 'package', package: '@tanstack/router-core', name: 'Redirect' },
            { from: 'package', package: '@tanstack/router-core', name: 'NotFoundError' },
          ],
        },
      ],
    },
  },

  // Config files run in Node and are outside the app's tsconfig project. Two objects, not one:
  // the spread carries its own languageOptions, so merging it in place would drop one side.
  { files: ['*.config.{ts,js}'], ...tseslint.configs.disableTypeChecked },
  { files: ['*.config.{ts,js}'], languageOptions: { globals: globals.node } },

  // Same treatment for the authoring scripts, and for the same reason: `tsconfig.json` includes
  // only `src` plus the two configs, so with `projectService: true` the parser has no program for
  // anything under `scripts/` and errors before it lints a line.
  { files: ['scripts/**/*.{ts,js,mjs}'], ...tseslint.configs.disableTypeChecked },
  { files: ['scripts/**/*.{ts,js,mjs}'], languageOptions: { globals: globals.node } },

  prettier,
);
